//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace HotFix.Data
{

/// <summary>
/// 奖励结构体
/// </summary>
public sealed partial class RewardStruct :  Bright.Config.BeanBase 
{
    public RewardStruct(JSONNode _json) 
    {
        { if(!_json["rewardType"].IsNumber) { throw new SerializationException(); }  RewardType = _json["rewardType"]; }
        { if(!_json["rewardId"].IsNumber) { throw new SerializationException(); }  RewardId = _json["rewardId"]; }
        { if(!_json["rewardNum"].IsNumber) { throw new SerializationException(); }  RewardNum = _json["rewardNum"]; }
        PostInit();
    }

    public RewardStruct(int rewardType, int rewardId, int rewardNum ) 
    {
        this.RewardType = rewardType;
        this.RewardId = rewardId;
        this.RewardNum = rewardNum;
        PostInit();
    }

    public static RewardStruct DeserializeRewardStruct(JSONNode _json)
    {
        return new RewardStruct(_json);
    }

    public int RewardType { get; private set; }
    public int RewardId { get; private set; }
    public int RewardNum { get; private set; }

    public const int __ID__ = 1906490372;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RewardType:" + RewardType + ","
        + "RewardId:" + RewardId + ","
        + "RewardNum:" + RewardNum + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
