//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace HotFix.Data
{
   
public sealed partial class Tables
{
    public Mail Mail {get; }
    public Item Item {get; }
    public Reward Reward {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        Mail = new Mail(loader("mail")); 
        tables.Add("Mail", Mail);
        Item = new Item(loader("item")); 
        tables.Add("Item", Item);
        Reward = new Reward(loader("reward")); 
        tables.Add("Reward", Reward);
        PostInit();

        Mail.Resolve(tables); 
        Item.Resolve(tables); 
        Reward.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        Mail.TranslateText(translator); 
        Item.TranslateText(translator); 
        Reward.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
