//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed partial class Tables
{
    public item.TbItem TbItem {get; }
    public WL_Excel.TbBuildingType TbBuildingType {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TbBuildingType = new WL_Excel.TbBuildingType(loader("wl_excel_tbbuildingtype")); 
        tables.Add("WL_Excel.TbBuildingType", TbBuildingType);
        PostInit();

        TbItem.Resolve(tables); 
        TbBuildingType.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbBuildingType.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
