// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommandCode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Linekong.Game.Message.Proto {

  /// <summary>Holder for reflection information generated from CommandCode.proto</summary>
  public static partial class CommandCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for CommandCode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb21tYW5kQ29kZS5wcm90bxIfY29tLmxpbmVrb25nLmdhbWUubWVzc2Fn",
            "ZS5wcm90bypFCgxDT01NQU5EX0NPREUSCwoHQ09NTUFORBAAEhQKD0lEX0xv",
            "Z2luUmVxdWVzdBCRThISCg1JRF9Mb2dpblJlcGx5EJJOYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Linekong.Game.Message.Proto.COMMAND_CODE), }, null));
    }
    #endregion

  }
  #region Enums
  public enum COMMAND_CODE {
    [pbr::OriginalName("COMMAND")] Command = 0,
    [pbr::OriginalName("ID_LoginRequest")] IdLoginRequest = 10001,
    [pbr::OriginalName("ID_LoginReply")] IdLoginReply = 10002,
  }

  #endregion

}

#endregion Designer generated code
