// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MailService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HotFix.Proto {

  /// <summary>Holder for reflection information generated from MailService.proto</summary>
  public static partial class MailServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for MailService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MailServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNYWlsU2VydmljZS5wcm90bxIMaG90Rml4LnByb3RvIj8KCkF0dGFjaG1l",
            "bnQSDgoGaXRlbUlkGAEgASgFEhAKCGl0ZW1UeXBlGAIgASgFEg8KB2l0ZW1O",
            "dW0YAyABKAUiwwEKCE1haWxJdGVtEg4KBm1haWxJZBgBIAEoAxIPCgdzdWJq",
            "ZWN0GAIgASgJEg8KB2NvbnRlbnQYAyABKAkSDgoGc2VuZElkGAQgASgDEg4K",
            "BnJlY3ZJZBgFIAEoAxISCgpjcmVhdGVUaW1lGAYgASgDEhAKCHJlYWRUaW1l",
            "GAcgASgDEiwKCmF0dGFjaG1lbnQYCCADKAsyGC5ob3RGaXgucHJvdG8uQXR0",
            "YWNobWVudBIRCglpc0RlbGV0ZWQYCSABKAgiVAoKTWFpbFN0YXR1cxIPCgdo",
            "YXNSZWFkGAEgASgIEhEKCWhhc0F0dGFjaBgCIAEoCBIPCgdpc0VtcHR5GAMg",
            "ASgIEhEKCWlzRGVsZXRlZBgEIAEoCCKWAQoKUGxheWVyTWFpbBIwCgRtYWls",
            "GAEgAygLMiIuaG90Rml4LnByb3RvLlBsYXllck1haWwuTWFpbEVudHJ5Eg8K",
            "B3JlbW92ZWQYAiADKAMaRQoJTWFpbEVudHJ5EgsKA2tleRgBIAEoAxInCgV2",
            "YWx1ZRgCIAEoCzIYLmhvdEZpeC5wcm90by5NYWlsU3RhdHVzOgI4ASIxCg9N",
            "YWlsTGlzdFJlcXVlc3QSEAoIcGxheWVySWQYASABKAMSDAoEbWFpbBgCIAMo",
            "AyJLCg1NYWlsTGlzdFJlcGx5EhAKCHBsYXllcklkGAEgASgDEigKCG1haWxJ",
            "dGVtGAIgAygLMhYuaG90Rml4LnByb3RvLk1haWxJdGVtIk8KEUNyZWF0ZU1h",
            "aWxSZXF1ZXN0EhAKCHBsYXllcklkGAEgASgDEigKCG1haWxJdGVtGAIgASgL",
            "MhYuaG90Rml4LnByb3RvLk1haWxJdGVtIjAKD0NyZWF0ZU1haWxSZXBseRIN",
            "CgVlcnJubxgBIAEoBRIOCgZtYWlsSWQYAiABKAMiOgoOTWFpbFJlY3ZOb3Rp",
            "ZnkSKAoIbWFpbEl0ZW0YASABKAsyFi5ob3RGaXgucHJvdG8uTWFpbEl0ZW0i",
            "MwoPUmVhZE1haWxSZXF1ZXN0EhAKCHBsYXllcklkGAEgASgDEg4KBm1haWxJ",
            "ZBgCIAEoAyIhCg1SZWFkTWFpbFJlcGx5EhAKCHJlYWRUaW1lGAEgASgDImIK",
            "EEdldEF0dGFjaFJlcXVlc3QSEAoIcGxheWVySWQYASABKAMSDgoGbWFpbElk",
            "GAIgASgDEiwKCmF0dGFjaG1lbnQYAyADKAsyGC5ob3RGaXgucHJvdG8uQXR0",
            "YWNobWVudCJOCg5HZXRBdHRhY2hSZXBseRIOCgZtYWlsSWQYASABKAMSLAoK",
            "YXR0YWNobWVudBgCIAMoCzIYLmhvdEZpeC5wcm90by5BdHRhY2htZW50IjUK",
            "EVJlbW92ZU1haWxSZXF1ZXN0EhAKCHBsYXllcklkGAEgASgDEg4KBm1haWxJ",
            "ZBgCIAEoAyIwCg9SZW1vdmVNYWlsUmVwbHkSDQoFZXJybm8YASABKAUSDgoG",
            "bWFpbElkGAIgASgDIjIKC1F1ZXJ5TWFpbERCEhAKCHBsYXllcklkGAEgASgD",
            "EhEKCWdhdGV3YXlJZBgCIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.Attachment), global::HotFix.Proto.Attachment.Parser, new[]{ "ItemId", "ItemType", "ItemNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.MailItem), global::HotFix.Proto.MailItem.Parser, new[]{ "MailId", "Subject", "Content", "SendId", "RecvId", "CreateTime", "ReadTime", "Attachment", "IsDeleted" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.MailStatus), global::HotFix.Proto.MailStatus.Parser, new[]{ "HasRead", "HasAttach", "IsEmpty", "IsDeleted" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.PlayerMail), global::HotFix.Proto.PlayerMail.Parser, new[]{ "Mail", "Removed" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.MailListRequest), global::HotFix.Proto.MailListRequest.Parser, new[]{ "PlayerId", "Mail" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.MailListReply), global::HotFix.Proto.MailListReply.Parser, new[]{ "PlayerId", "MailItem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.CreateMailRequest), global::HotFix.Proto.CreateMailRequest.Parser, new[]{ "PlayerId", "MailItem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.CreateMailReply), global::HotFix.Proto.CreateMailReply.Parser, new[]{ "Errno", "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.MailRecvNotify), global::HotFix.Proto.MailRecvNotify.Parser, new[]{ "MailItem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.ReadMailRequest), global::HotFix.Proto.ReadMailRequest.Parser, new[]{ "PlayerId", "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.ReadMailReply), global::HotFix.Proto.ReadMailReply.Parser, new[]{ "ReadTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.GetAttachRequest), global::HotFix.Proto.GetAttachRequest.Parser, new[]{ "PlayerId", "MailId", "Attachment" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.GetAttachReply), global::HotFix.Proto.GetAttachReply.Parser, new[]{ "MailId", "Attachment" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.RemoveMailRequest), global::HotFix.Proto.RemoveMailRequest.Parser, new[]{ "PlayerId", "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.RemoveMailReply), global::HotFix.Proto.RemoveMailReply.Parser, new[]{ "Errno", "MailId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HotFix.Proto.QueryMailDB), global::HotFix.Proto.QueryMailDB.Parser, new[]{ "PlayerId", "GatewayId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Attachment : pb::IMessage<Attachment> {
    private static readonly pb::MessageParser<Attachment> _parser = new pb::MessageParser<Attachment>(() => new Attachment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Attachment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attachment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attachment(Attachment other) : this() {
      itemId_ = other.itemId_;
      itemType_ = other.itemType_;
      itemNum_ = other.itemNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attachment Clone() {
      return new Attachment(this);
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 1;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 2;
    private int itemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "itemNum" field.</summary>
    public const int ItemNumFieldNumber = 3;
    private int itemNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemNum {
      get { return itemNum_; }
      set {
        itemNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Attachment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Attachment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemId != other.ItemId) return false;
      if (ItemType != other.ItemType) return false;
      if (ItemNum != other.ItemNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (ItemType != 0) hash ^= ItemType.GetHashCode();
      if (ItemNum != 0) hash ^= ItemNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemId);
      }
      if (ItemType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemType);
      }
      if (ItemNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (ItemType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemType);
      }
      if (ItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Attachment other) {
      if (other == null) {
        return;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.ItemType != 0) {
        ItemType = other.ItemType;
      }
      if (other.ItemNum != 0) {
        ItemNum = other.ItemNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemId = input.ReadInt32();
            break;
          }
          case 16: {
            ItemType = input.ReadInt32();
            break;
          }
          case 24: {
            ItemNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MailItem : pb::IMessage<MailItem> {
    private static readonly pb::MessageParser<MailItem> _parser = new pb::MessageParser<MailItem>(() => new MailItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailItem(MailItem other) : this() {
      mailId_ = other.mailId_;
      subject_ = other.subject_;
      content_ = other.content_;
      sendId_ = other.sendId_;
      recvId_ = other.recvId_;
      createTime_ = other.createTime_;
      readTime_ = other.readTime_;
      attachment_ = other.attachment_.Clone();
      isDeleted_ = other.isDeleted_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailItem Clone() {
      return new MailItem(this);
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private long mailId_;
    /// <summary>
    ///邮件ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    /// <summary>Field number for the "subject" field.</summary>
    public const int SubjectFieldNumber = 2;
    private string subject_ = "";
    /// <summary>
    ///标题
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Subject {
      get { return subject_; }
      set {
        subject_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 3;
    private string content_ = "";
    /// <summary>
    ///邮件内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sendId" field.</summary>
    public const int SendIdFieldNumber = 4;
    private long sendId_;
    /// <summary>
    ///发件人ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SendId {
      get { return sendId_; }
      set {
        sendId_ = value;
      }
    }

    /// <summary>Field number for the "recvId" field.</summary>
    public const int RecvIdFieldNumber = 5;
    private long recvId_;
    /// <summary>
    ///收件人ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RecvId {
      get { return recvId_; }
      set {
        recvId_ = value;
      }
    }

    /// <summary>Field number for the "createTime" field.</summary>
    public const int CreateTimeFieldNumber = 6;
    private long createTime_;
    /// <summary>
    ///发送时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "readTime" field.</summary>
    public const int ReadTimeFieldNumber = 7;
    private long readTime_;
    /// <summary>
    ///读取时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ReadTime {
      get { return readTime_; }
      set {
        readTime_ = value;
      }
    }

    /// <summary>Field number for the "attachment" field.</summary>
    public const int AttachmentFieldNumber = 8;
    private static readonly pb::FieldCodec<global::HotFix.Proto.Attachment> _repeated_attachment_codec
        = pb::FieldCodec.ForMessage(66, global::HotFix.Proto.Attachment.Parser);
    private readonly pbc::RepeatedField<global::HotFix.Proto.Attachment> attachment_ = new pbc::RepeatedField<global::HotFix.Proto.Attachment>();
    /// <summary>
    /// 附件列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HotFix.Proto.Attachment> Attachment {
      get { return attachment_; }
    }

    /// <summary>Field number for the "isDeleted" field.</summary>
    public const int IsDeletedFieldNumber = 9;
    private bool isDeleted_;
    /// <summary>
    /// 删除标记
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsDeleted {
      get { return isDeleted_; }
      set {
        isDeleted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MailItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MailItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      if (Subject != other.Subject) return false;
      if (Content != other.Content) return false;
      if (SendId != other.SendId) return false;
      if (RecvId != other.RecvId) return false;
      if (CreateTime != other.CreateTime) return false;
      if (ReadTime != other.ReadTime) return false;
      if(!attachment_.Equals(other.attachment_)) return false;
      if (IsDeleted != other.IsDeleted) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      if (Subject.Length != 0) hash ^= Subject.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (SendId != 0L) hash ^= SendId.GetHashCode();
      if (RecvId != 0L) hash ^= RecvId.GetHashCode();
      if (CreateTime != 0L) hash ^= CreateTime.GetHashCode();
      if (ReadTime != 0L) hash ^= ReadTime.GetHashCode();
      hash ^= attachment_.GetHashCode();
      if (IsDeleted != false) hash ^= IsDeleted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MailId);
      }
      if (Subject.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Subject);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Content);
      }
      if (SendId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SendId);
      }
      if (RecvId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RecvId);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(CreateTime);
      }
      if (ReadTime != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(ReadTime);
      }
      attachment_.WriteTo(output, _repeated_attachment_codec);
      if (IsDeleted != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (Subject.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Subject);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (SendId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SendId);
      }
      if (RecvId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RecvId);
      }
      if (CreateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateTime);
      }
      if (ReadTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReadTime);
      }
      size += attachment_.CalculateSize(_repeated_attachment_codec);
      if (IsDeleted != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MailItem other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      if (other.Subject.Length != 0) {
        Subject = other.Subject;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.SendId != 0L) {
        SendId = other.SendId;
      }
      if (other.RecvId != 0L) {
        RecvId = other.RecvId;
      }
      if (other.CreateTime != 0L) {
        CreateTime = other.CreateTime;
      }
      if (other.ReadTime != 0L) {
        ReadTime = other.ReadTime;
      }
      attachment_.Add(other.attachment_);
      if (other.IsDeleted != false) {
        IsDeleted = other.IsDeleted;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt64();
            break;
          }
          case 18: {
            Subject = input.ReadString();
            break;
          }
          case 26: {
            Content = input.ReadString();
            break;
          }
          case 32: {
            SendId = input.ReadInt64();
            break;
          }
          case 40: {
            RecvId = input.ReadInt64();
            break;
          }
          case 48: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 56: {
            ReadTime = input.ReadInt64();
            break;
          }
          case 66: {
            attachment_.AddEntriesFrom(input, _repeated_attachment_codec);
            break;
          }
          case 72: {
            IsDeleted = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MailStatus : pb::IMessage<MailStatus> {
    private static readonly pb::MessageParser<MailStatus> _parser = new pb::MessageParser<MailStatus>(() => new MailStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailStatus(MailStatus other) : this() {
      hasRead_ = other.hasRead_;
      hasAttach_ = other.hasAttach_;
      isEmpty_ = other.isEmpty_;
      isDeleted_ = other.isDeleted_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailStatus Clone() {
      return new MailStatus(this);
    }

    /// <summary>Field number for the "hasRead" field.</summary>
    public const int HasReadFieldNumber = 1;
    private bool hasRead_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasRead {
      get { return hasRead_; }
      set {
        hasRead_ = value;
      }
    }

    /// <summary>Field number for the "hasAttach" field.</summary>
    public const int HasAttachFieldNumber = 2;
    private bool hasAttach_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasAttach {
      get { return hasAttach_; }
      set {
        hasAttach_ = value;
      }
    }

    /// <summary>Field number for the "isEmpty" field.</summary>
    public const int IsEmptyFieldNumber = 3;
    private bool isEmpty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsEmpty {
      get { return isEmpty_; }
      set {
        isEmpty_ = value;
      }
    }

    /// <summary>Field number for the "isDeleted" field.</summary>
    public const int IsDeletedFieldNumber = 4;
    private bool isDeleted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsDeleted {
      get { return isDeleted_; }
      set {
        isDeleted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MailStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MailStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HasRead != other.HasRead) return false;
      if (HasAttach != other.HasAttach) return false;
      if (IsEmpty != other.IsEmpty) return false;
      if (IsDeleted != other.IsDeleted) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRead != false) hash ^= HasRead.GetHashCode();
      if (HasAttach != false) hash ^= HasAttach.GetHashCode();
      if (IsEmpty != false) hash ^= IsEmpty.GetHashCode();
      if (IsDeleted != false) hash ^= IsDeleted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasRead != false) {
        output.WriteRawTag(8);
        output.WriteBool(HasRead);
      }
      if (HasAttach != false) {
        output.WriteRawTag(16);
        output.WriteBool(HasAttach);
      }
      if (IsEmpty != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsEmpty);
      }
      if (IsDeleted != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasRead != false) {
        size += 1 + 1;
      }
      if (HasAttach != false) {
        size += 1 + 1;
      }
      if (IsEmpty != false) {
        size += 1 + 1;
      }
      if (IsDeleted != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MailStatus other) {
      if (other == null) {
        return;
      }
      if (other.HasRead != false) {
        HasRead = other.HasRead;
      }
      if (other.HasAttach != false) {
        HasAttach = other.HasAttach;
      }
      if (other.IsEmpty != false) {
        IsEmpty = other.IsEmpty;
      }
      if (other.IsDeleted != false) {
        IsDeleted = other.IsDeleted;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HasRead = input.ReadBool();
            break;
          }
          case 16: {
            HasAttach = input.ReadBool();
            break;
          }
          case 24: {
            IsEmpty = input.ReadBool();
            break;
          }
          case 32: {
            IsDeleted = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerMail : pb::IMessage<PlayerMail> {
    private static readonly pb::MessageParser<PlayerMail> _parser = new pb::MessageParser<PlayerMail>(() => new PlayerMail());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerMail> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMail() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMail(PlayerMail other) : this() {
      mail_ = other.mail_.Clone();
      removed_ = other.removed_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerMail Clone() {
      return new PlayerMail(this);
    }

    /// <summary>Field number for the "mail" field.</summary>
    public const int MailFieldNumber = 1;
    private static readonly pbc::MapField<long, global::HotFix.Proto.MailStatus>.Codec _map_mail_codec
        = new pbc::MapField<long, global::HotFix.Proto.MailStatus>.Codec(pb::FieldCodec.ForInt64(8), pb::FieldCodec.ForMessage(18, global::HotFix.Proto.MailStatus.Parser), 10);
    private readonly pbc::MapField<long, global::HotFix.Proto.MailStatus> mail_ = new pbc::MapField<long, global::HotFix.Proto.MailStatus>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<long, global::HotFix.Proto.MailStatus> Mail {
      get { return mail_; }
    }

    /// <summary>Field number for the "removed" field.</summary>
    public const int RemovedFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_removed_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> removed_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> Removed {
      get { return removed_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerMail);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerMail other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Mail.Equals(other.Mail)) return false;
      if(!removed_.Equals(other.removed_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Mail.GetHashCode();
      hash ^= removed_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mail_.WriteTo(output, _map_mail_codec);
      removed_.WriteTo(output, _repeated_removed_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mail_.CalculateSize(_map_mail_codec);
      size += removed_.CalculateSize(_repeated_removed_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerMail other) {
      if (other == null) {
        return;
      }
      mail_.Add(other.mail_);
      removed_.Add(other.removed_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mail_.AddEntriesFrom(input, _map_mail_codec);
            break;
          }
          case 18:
          case 16: {
            removed_.AddEntriesFrom(input, _repeated_removed_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MailListRequest : pb::IMessage<MailListRequest> {
    private static readonly pb::MessageParser<MailListRequest> _parser = new pb::MessageParser<MailListRequest>(() => new MailListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListRequest(MailListRequest other) : this() {
      playerId_ = other.playerId_;
      mail_ = other.mail_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListRequest Clone() {
      return new MailListRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mail" field.</summary>
    public const int MailFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_mail_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> mail_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> Mail {
      get { return mail_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MailListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MailListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if(!mail_.Equals(other.mail_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      hash ^= mail_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      mail_.WriteTo(output, _repeated_mail_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      size += mail_.CalculateSize(_repeated_mail_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MailListRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      mail_.Add(other.mail_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 18:
          case 16: {
            mail_.AddEntriesFrom(input, _repeated_mail_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MailListReply : pb::IMessage<MailListReply> {
    private static readonly pb::MessageParser<MailListReply> _parser = new pb::MessageParser<MailListReply>(() => new MailListReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailListReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListReply(MailListReply other) : this() {
      playerId_ = other.playerId_;
      mailItem_ = other.mailItem_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailListReply Clone() {
      return new MailListReply(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mailItem" field.</summary>
    public const int MailItemFieldNumber = 2;
    private static readonly pb::FieldCodec<global::HotFix.Proto.MailItem> _repeated_mailItem_codec
        = pb::FieldCodec.ForMessage(18, global::HotFix.Proto.MailItem.Parser);
    private readonly pbc::RepeatedField<global::HotFix.Proto.MailItem> mailItem_ = new pbc::RepeatedField<global::HotFix.Proto.MailItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HotFix.Proto.MailItem> MailItem {
      get { return mailItem_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MailListReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MailListReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if(!mailItem_.Equals(other.mailItem_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      hash ^= mailItem_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      mailItem_.WriteTo(output, _repeated_mailItem_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      size += mailItem_.CalculateSize(_repeated_mailItem_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MailListReply other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      mailItem_.Add(other.mailItem_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 18: {
            mailItem_.AddEntriesFrom(input, _repeated_mailItem_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateMailRequest : pb::IMessage<CreateMailRequest> {
    private static readonly pb::MessageParser<CreateMailRequest> _parser = new pb::MessageParser<CreateMailRequest>(() => new CreateMailRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateMailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailRequest(CreateMailRequest other) : this() {
      playerId_ = other.playerId_;
      mailItem_ = other.mailItem_ != null ? other.mailItem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailRequest Clone() {
      return new CreateMailRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mailItem" field.</summary>
    public const int MailItemFieldNumber = 2;
    private global::HotFix.Proto.MailItem mailItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::HotFix.Proto.MailItem MailItem {
      get { return mailItem_; }
      set {
        mailItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateMailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateMailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(MailItem, other.MailItem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (mailItem_ != null) hash ^= MailItem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (mailItem_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MailItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (mailItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MailItem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateMailRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.mailItem_ != null) {
        if (mailItem_ == null) {
          MailItem = new global::HotFix.Proto.MailItem();
        }
        MailItem.MergeFrom(other.MailItem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 18: {
            if (mailItem_ == null) {
              MailItem = new global::HotFix.Proto.MailItem();
            }
            input.ReadMessage(MailItem);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateMailReply : pb::IMessage<CreateMailReply> {
    private static readonly pb::MessageParser<CreateMailReply> _parser = new pb::MessageParser<CreateMailReply>(() => new CreateMailReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateMailReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailReply(CreateMailReply other) : this() {
      errno_ = other.errno_;
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateMailReply Clone() {
      return new CreateMailReply(this);
    }

    /// <summary>Field number for the "errno" field.</summary>
    public const int ErrnoFieldNumber = 1;
    private int errno_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Errno {
      get { return errno_; }
      set {
        errno_ = value;
      }
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 2;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateMailReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateMailReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Errno != other.Errno) return false;
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Errno != 0) hash ^= Errno.GetHashCode();
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Errno != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Errno);
      }
      if (MailId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Errno != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Errno);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateMailReply other) {
      if (other == null) {
        return;
      }
      if (other.Errno != 0) {
        Errno = other.Errno;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Errno = input.ReadInt32();
            break;
          }
          case 16: {
            MailId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MailRecvNotify : pb::IMessage<MailRecvNotify> {
    private static readonly pb::MessageParser<MailRecvNotify> _parser = new pb::MessageParser<MailRecvNotify>(() => new MailRecvNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailRecvNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailRecvNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailRecvNotify(MailRecvNotify other) : this() {
      mailItem_ = other.mailItem_ != null ? other.mailItem_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MailRecvNotify Clone() {
      return new MailRecvNotify(this);
    }

    /// <summary>Field number for the "mailItem" field.</summary>
    public const int MailItemFieldNumber = 1;
    private global::HotFix.Proto.MailItem mailItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::HotFix.Proto.MailItem MailItem {
      get { return mailItem_; }
      set {
        mailItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MailRecvNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MailRecvNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MailItem, other.MailItem)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mailItem_ != null) hash ^= MailItem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mailItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MailItem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mailItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MailItem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MailRecvNotify other) {
      if (other == null) {
        return;
      }
      if (other.mailItem_ != null) {
        if (mailItem_ == null) {
          MailItem = new global::HotFix.Proto.MailItem();
        }
        MailItem.MergeFrom(other.MailItem);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mailItem_ == null) {
              MailItem = new global::HotFix.Proto.MailItem();
            }
            input.ReadMessage(MailItem);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReadMailRequest : pb::IMessage<ReadMailRequest> {
    private static readonly pb::MessageParser<ReadMailRequest> _parser = new pb::MessageParser<ReadMailRequest>(() => new ReadMailRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReadMailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailRequest(ReadMailRequest other) : this() {
      playerId_ = other.playerId_;
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailRequest Clone() {
      return new ReadMailRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 2;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReadMailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReadMailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (MailId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReadMailRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            MailId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReadMailReply : pb::IMessage<ReadMailReply> {
    private static readonly pb::MessageParser<ReadMailReply> _parser = new pb::MessageParser<ReadMailReply>(() => new ReadMailReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReadMailReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailReply(ReadMailReply other) : this() {
      readTime_ = other.readTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReadMailReply Clone() {
      return new ReadMailReply(this);
    }

    /// <summary>Field number for the "readTime" field.</summary>
    public const int ReadTimeFieldNumber = 1;
    private long readTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ReadTime {
      get { return readTime_; }
      set {
        readTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReadMailReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReadMailReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReadTime != other.ReadTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReadTime != 0L) hash ^= ReadTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ReadTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ReadTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReadTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ReadTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReadMailReply other) {
      if (other == null) {
        return;
      }
      if (other.ReadTime != 0L) {
        ReadTime = other.ReadTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReadTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAttachRequest : pb::IMessage<GetAttachRequest> {
    private static readonly pb::MessageParser<GetAttachRequest> _parser = new pb::MessageParser<GetAttachRequest>(() => new GetAttachRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAttachRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachRequest(GetAttachRequest other) : this() {
      playerId_ = other.playerId_;
      mailId_ = other.mailId_;
      attachment_ = other.attachment_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachRequest Clone() {
      return new GetAttachRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 2;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    /// <summary>Field number for the "attachment" field.</summary>
    public const int AttachmentFieldNumber = 3;
    private static readonly pb::FieldCodec<global::HotFix.Proto.Attachment> _repeated_attachment_codec
        = pb::FieldCodec.ForMessage(26, global::HotFix.Proto.Attachment.Parser);
    private readonly pbc::RepeatedField<global::HotFix.Proto.Attachment> attachment_ = new pbc::RepeatedField<global::HotFix.Proto.Attachment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HotFix.Proto.Attachment> Attachment {
      get { return attachment_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAttachRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAttachRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (MailId != other.MailId) return false;
      if(!attachment_.Equals(other.attachment_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      hash ^= attachment_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (MailId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MailId);
      }
      attachment_.WriteTo(output, _repeated_attachment_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      size += attachment_.CalculateSize(_repeated_attachment_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAttachRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      attachment_.Add(other.attachment_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            MailId = input.ReadInt64();
            break;
          }
          case 26: {
            attachment_.AddEntriesFrom(input, _repeated_attachment_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAttachReply : pb::IMessage<GetAttachReply> {
    private static readonly pb::MessageParser<GetAttachReply> _parser = new pb::MessageParser<GetAttachReply>(() => new GetAttachReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAttachReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachReply(GetAttachReply other) : this() {
      mailId_ = other.mailId_;
      attachment_ = other.attachment_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAttachReply Clone() {
      return new GetAttachReply(this);
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 1;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    /// <summary>Field number for the "attachment" field.</summary>
    public const int AttachmentFieldNumber = 2;
    private static readonly pb::FieldCodec<global::HotFix.Proto.Attachment> _repeated_attachment_codec
        = pb::FieldCodec.ForMessage(18, global::HotFix.Proto.Attachment.Parser);
    private readonly pbc::RepeatedField<global::HotFix.Proto.Attachment> attachment_ = new pbc::RepeatedField<global::HotFix.Proto.Attachment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HotFix.Proto.Attachment> Attachment {
      get { return attachment_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAttachReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAttachReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MailId != other.MailId) return false;
      if(!attachment_.Equals(other.attachment_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      hash ^= attachment_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(MailId);
      }
      attachment_.WriteTo(output, _repeated_attachment_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      size += attachment_.CalculateSize(_repeated_attachment_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAttachReply other) {
      if (other == null) {
        return;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      attachment_.Add(other.attachment_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MailId = input.ReadInt64();
            break;
          }
          case 18: {
            attachment_.AddEntriesFrom(input, _repeated_attachment_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RemoveMailRequest : pb::IMessage<RemoveMailRequest> {
    private static readonly pb::MessageParser<RemoveMailRequest> _parser = new pb::MessageParser<RemoveMailRequest>(() => new RemoveMailRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoveMailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailRequest(RemoveMailRequest other) : this() {
      playerId_ = other.playerId_;
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailRequest Clone() {
      return new RemoveMailRequest(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 2;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoveMailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoveMailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (MailId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoveMailRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            MailId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RemoveMailReply : pb::IMessage<RemoveMailReply> {
    private static readonly pb::MessageParser<RemoveMailReply> _parser = new pb::MessageParser<RemoveMailReply>(() => new RemoveMailReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemoveMailReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailReply(RemoveMailReply other) : this() {
      errno_ = other.errno_;
      mailId_ = other.mailId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemoveMailReply Clone() {
      return new RemoveMailReply(this);
    }

    /// <summary>Field number for the "errno" field.</summary>
    public const int ErrnoFieldNumber = 1;
    private int errno_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Errno {
      get { return errno_; }
      set {
        errno_ = value;
      }
    }

    /// <summary>Field number for the "mailId" field.</summary>
    public const int MailIdFieldNumber = 2;
    private long mailId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long MailId {
      get { return mailId_; }
      set {
        mailId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemoveMailReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemoveMailReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Errno != other.Errno) return false;
      if (MailId != other.MailId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Errno != 0) hash ^= Errno.GetHashCode();
      if (MailId != 0L) hash ^= MailId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Errno != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Errno);
      }
      if (MailId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Errno != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Errno);
      }
      if (MailId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MailId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemoveMailReply other) {
      if (other == null) {
        return;
      }
      if (other.Errno != 0) {
        Errno = other.Errno;
      }
      if (other.MailId != 0L) {
        MailId = other.MailId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Errno = input.ReadInt32();
            break;
          }
          case 16: {
            MailId = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class QueryMailDB : pb::IMessage<QueryMailDB> {
    private static readonly pb::MessageParser<QueryMailDB> _parser = new pb::MessageParser<QueryMailDB>(() => new QueryMailDB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryMailDB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HotFix.Proto.MailServiceReflection.Descriptor.MessageTypes[15]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMailDB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMailDB(QueryMailDB other) : this() {
      playerId_ = other.playerId_;
      gatewayId_ = other.gatewayId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryMailDB Clone() {
      return new QueryMailDB(this);
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "gatewayId" field.</summary>
    public const int GatewayIdFieldNumber = 2;
    private int gatewayId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GatewayId {
      get { return gatewayId_; }
      set {
        gatewayId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryMailDB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryMailDB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (GatewayId != other.GatewayId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (GatewayId != 0) hash ^= GatewayId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (GatewayId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GatewayId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (GatewayId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GatewayId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryMailDB other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.GatewayId != 0) {
        GatewayId = other.GatewayId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            GatewayId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
