//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace HotFix.Data
{

public sealed partial class Language
{
    private readonly Dictionary<int, LanguageData> _dataMap;
    private readonly List<LanguageData> _dataList;
    
    public Language(JSONNode _json)
    {
        _dataMap = new Dictionary<int, LanguageData>();
        _dataList = new List<LanguageData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = LanguageData.DeserializeLanguageData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Tag, _v);
        }
        PostInit();
    }

    //public Dictionary<int, LanguageData> DataMap => _dataMap;
    public List<LanguageData> DataList => _dataList;

    public LanguageData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    //public LanguageData Get(int key) => _dataMap[key];
    //public LanguageData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}