//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace HotFix.Data
{

/// <summary>
/// 主动使用道具参数
/// </summary>
public sealed partial class UserItemStruct :  Bright.Config.BeanBase 
{
    public UserItemStruct(JSONNode _json) 
    {
        { if(!_json["useType"].IsString) { throw new SerializationException(); }  UseType = _json["useType"]; }
        { if(!_json["useNum"].IsNumber) { throw new SerializationException(); }  UseNum = _json["useNum"]; }
        PostInit();
    }

    public UserItemStruct(string useType, int useNum ) 
    {
        this.UseType = useType;
        this.UseNum = useNum;
        PostInit();
    }

    public static UserItemStruct DeserializeUserItemStruct(JSONNode _json)
    {
        return new UserItemStruct(_json);
    }

    public string UseType { get; private set; }
    public int UseNum { get; private set; }

    public const int __ID__ = 1752804115;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UseType:" + UseType + ","
        + "UseNum:" + UseNum + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
